# -*- coding: utf-8 -*-
"""
Created on Wed Jul 24 16:32:33 2024

@author: ADearling

gorgon_import class for importing pvti files generated by Gorgon 
"""

#%% Libraries

from pathlib import Path
import numpy as np
import pandas as pd
import re
import vtk
from vtk.util import numpy_support as vtk_np
import grid


#%% Functions and classes

class ChimeraSimulation:

    def __init__(self, rootdir, project, simulation=None,
                 suffix='pvti', geometry=None, verbose=False):
        
        self.rootdir = Path(rootdir)
        self.project = project
        
        self.simulation = simulation
        
        self.suffix = suffix
        self.geometry = geometry
        self.verbose = verbose
        
        self.arr_names = None
        self.arr = {}
        
        self._load_files()
        
    
    def get_run_details(self):
        '''Read run_details.txt'''

        file_path = self.rootdir / self.project / "run_details.txt"
        
        if not file_path.exists():
            raise FileNotFoundError("run_details.txt does not exist in target directory.")
        
        run_details = pd.read_csv(file_path, sep=',')
        
        return run_details


    def load_dat(self, simulation=None, external_file = None, columns=[], time_window=(None,None), monotonic=True):
        '''Load the Chimera .dat file for a given run as a pandas df.'''
        
        if simulation is None:
            simulation = self.simulation
            
        if simulation is None:
            raise Exception("Simulation must be specified.")
        
        if external_file is None:
            external_file = simulation
        
        file_path = self.rootdir / self.project / simulation / (external_file + ".dat")

        dat_df = pd.read_csv(file_path, sep=r'\s+')
        
        dat_df = dat_df[dat_df.ne(dat_df.columns).any(axis=1)]
        
        if monotonic and external_file is None: # Force time to be monotonic in case of restarts
        
            time = dat_df["time"].to_numpy(dtype='float32')
        
            indices = np.where(np.diff(time) <= 0)[0] + 1
            
            if indices.size == 0:
                groups = []
            else:
                groups = np.split(indices, np.where(np.diff(indices) != 1)[0] + 1)
                print(f"Data contains {len(groups)} restart(s).")
            
            delete_indices = []
            
            for group in groups:
                for i in range(group[-1]):
                    if time[i] >= time[group[-1]]:
                        delete_indices.append(i)
            
            dat_df.drop(index=dat_df.index[delete_indices], inplace=True)
            
        dat_df = dat_df.astype(float) # All data in .dat should be a float (unless NaN)
           
        if time_window[0] is not None:
            dat_df = dat_df[(dat_df["time"] >= time_window[0])]
        if time_window[1] is not None:
            dat_df = dat_df[(dat_df["time"] <= time_window[1])]
        
        if len(columns) > 0:
            return dat_df[columns]
    
        else:
            return dat_df


    def _create_filename(self, arr_name, output=None, nodir=False):
        '''Construct file name for importing'''
        
        # If time is not given, read from class
        if(output is None):
            output = self.output

        if not isinstance(output, str):
            output = str(output)

        # Construct the filename only
        filename = f"{self.index}_{arr_name}-{output}.{self.suffix}"
    
        # Construct directory as Path
        fdir = self.run_path / "vti"
    
        # If nodir, return only the filename
        # if nodir:
        #     return filename
    
        # Full path
        return fdir / filename
    
    
    def load_simulation(self, simulation, suffix='pvti', geometry=None):
        '''Public, safe entry point.'''
        
        self._reset_simulation_state()
        self.simulation = simulation
        self.suffix = suffix
        self.geometry = geometry
        self._load_files()
    
    
    def _reset_simulation_state(self):
        '''Clear all attributes that depend on the simulation.'''
        
        self.run_path = None
        self.index = None
        self.arr_names = None
        self.outputs = None
        self.output = None
        self.suffix = 'pvti'
        self.geometry = None
        self.arr = {}
        
    
    def _load_files(self, simulation=None):
        '''If directory is provided, read in available variables/times/domain'''
        
        if simulation is not None: 
            self.simulation = simulation
            
        if self.simulation is None:
            return

        self.run_path = self.rootdir / self.project / self.simulation    
    
        folder = self.run_path / "vti"   # remove /"vti" if that's not intended
        files = list(folder.glob(f"*.{self.suffix}"))
        
        if not files:
            raise FileNotFoundError(
                f"No files found in target directory: {folder}/*.{self.suffix}"
            )
        
        file_names = [f.name for f in files]

        self.index = np.array([re.split('[_]', f)[0] for f in file_names])
        self.index = np.unique(self.index)[0]

        i = len(self.index)
        out = np.array([re.split('[.-]', f[i+1:]) for f in file_names])
        
        self.arr_names = np.unique(out[:, 0]) # All variables
        self.outputs = np.unique(out[:, 1:-1]) # All output timesteps (was removing 0th output)

        s = np.argsort([int(i) for i in self.outputs])
        self.outputs = self.outputs[s]

        # Import domain from first file that isn't Avec or Evec, or restart
        for s in self.arr_names:
            if(s not in ['Avec', 'Evec']):
                if(s[-7:]!="restart"):
                    break
        
        file_name = self._create_filename(s, self.outputs[0])
        self.import_space(file_name)
        self.output = self.outputs[0]

        if(self.verbose is True):
            print(self.index)
            print(self.arr_names)
            print(self.outputs)
            print(self.output)
        
        
    def import_space(self, filename):
        
        if not filename.is_file():
            print(f"Can't find file: {filename}")

        else:
            if self.verbose == True:
                print('filename = ', filename)
            
            if (self.suffix == 'pvti'):
                reader = vtk.vtkXMLPImageDataReader()
            elif (self.suffix == 'vti'):
                    reader = vtk.vtkXMLImageDataReader()
            elif (self.suffix == 'vts'):
                reader = vtk.vtkXMLStructuredGridReader()
            else:
                print('Not supported file type')
                
            reader.SetFileName(filename)
            reader.Update()
            data = reader.GetOutput() # Loads a dataset to get parameters.
            
            bounds = np.array(data.GetBounds()) # Lower and upper x, y and z COORDINATE values
            # print(' BOUNDS = ',bounds)
            # print('self.xc = ',bounds[0],bounds[2],bounds[4]))

            # dim = data.GetDimensions() # Number of cell boundaries - deprecated
            extent = data.GetExtent()
            dim = [extent[1] + 1, extent[3] + 1, extent[5] + 1]
            self.nx = extent[1] - extent[0]
            self.ny = extent[3] - extent[2]
            self.nz = extent[5] - extent[4]

            points = data.GetPoints()

            # Coordinates are given as a tuple (x,y,z) - imaging this shows the geometry of the object
            coordinates = np.array([points.GetPoint(i) for i in range(points.GetNumberOfPoints())])
            # self.coordinates = coordinates
            
            if self.suffix == 'vti':
                spacing = np.array(data.GetSpacing())
                self.d = spacing

                self.x = np.linspace(bounds[0], bounds[1], dim[0])
                self.y = np.linspace(bounds[2], bounds[3], dim[1])
                self.z = np.linspace(bounds[4], bounds[5], dim[2])
                
                self.xc = self.x[:-1] + spacing[0]/2
                self.yc = self.y[:-1] + spacing[1]/2
                self.zc = self.z[:-1] + spacing[2]/2

            else: # For vts files with cylidrical or spherical symmetry
                
                if self.geometry == 0: # Grid is not regular rectilinear
                    
                    self.x = np.unique(coordinates[:,0])
                    self.y = np.unique(coordinates[:,1])
                    self.z = np.unique(coordinates[:,2])

                elif self.geometry == 1:
                    
                    r, theta, __ = grid.convert_to_polar(coordinates)
                    
                    self.x = np.linspace(r.min(), r.max(), dim[0])
                    self.y = np.linspace(theta.min(), theta.max(), dim[1])
                    self.z = np.linspace(bounds[4], bounds[5], dim[2])
                    
                elif self.geometry == 2:
                    
                    r, theta, phi = grid.convert_to_spherical(coordinates)
                    
                    self.x = np.linspace(r.min(), r.max(), dim[0])
                    self.y = np.linspace(theta.min(), theta.max(), dim[1])
                    self.z = np.linspace(phi.min(), phi.max(), dim[2])
                    
                else:
                    raise Exception("Cannot distinguish between cylindrical and spherical symmetry.")

                # self.d = [self.x[1]-self.x[0], self.y[1]-self.y[0], self.z[1]-self.z[0]]
                self.d = [0, 0, 0]

                self.xc = (self.x[1:] + self.x[:-1])/2
                self.yc = (self.y[1:] + self.y[:-1])/2
                self.zc = (self.z[1:] + self.z[:-1])/2


    # def _format_variable(self, variable):
    #     '''Utility function for formatting variables'''
        
    #     if variable in ["Bx","By","Bz","Bmag"]:
    #         variable_f = "Bvec"
    #     elif variable in ["Ex","Ey","Ez"]:
    #         variable_f = "Hvec"
    #     elif variable == "Pe":
    #         variable_f = "array_pres_e"
    #     elif variable == "Pi":
    #         variable_f = "array_pres_i"
    #     elif variable in ["vx","vy","vz"]:
    #         variable_f = "vvec"
    #     else:
    #         variable_f = variable

    #     return variable_f
    
    
    # def _format_data(self, variable, data):
    #     '''
    #     Formats variable data structure.
        
    #     If data is expected to be provided on cell faces (e.g. the electric field)
    #     interpolation is performed.
    #     '''

    #     if variable == "Bx":
    #         data_f = data[:,:,:,0]
    #     elif variable == "By":
    #         data_f = data[:,:,:,1]
    #     elif variable == "Bz":
    #         data_f = data[:,:,:,2]
    #     elif variable == "Bmag":
    #         data_f = np.linalg.norm(data, axis=3)
    #     elif variable == "Ex":
    #         data_f = data[:,:,:,0]
    #     elif variable == "Ey":
    #         data_f = data[:,:,:,1]
    #     elif variable == "Ez":
    #         data_f = data[:,:,:,2]
    #     elif variable == "vx":
    #         data_f = data[:,:,:,0]
    #     elif variable == "vy":
    #         data_f = data[:,:,:,1]
    #     elif variable == "vz":
    #         data_f = data[:,:,:,2]
    #     else:
    #         data_f = data
            
    #     return data_f


    def import_timestep(self, i, arr_names=None, delete_existing=True):
        '''Function for adding Chimera data to class'''
        
        # Check that output is in directory
        try:
            # self.output = self.output[i]
            self.output = i
            # print("Importing {}th file = {} output.".format(i, self.outputs[i]))
        except:
            print("Timestep {} not in output directory. Using default ({}).".format(i,self.output))

        # Check that file search has been performed
        if self.arr_names is None:
            self._load_files()

        # If array name is not specified set import to all data
        if(arr_names is None):
            arr_names = self.arr_names

        # # Format variable name for search
        # arr_names_f = [self.format_variable(arr_name) for arr_name in arr_names]

        # Check that all variables are in output list
        for s in arr_names:
            if(s not in self.arr_names):
                raise Exception("Variable ({}) does not exist in output directory. ".format(s)+
                                "Available variables are: {}".format(self.arr_names))
    
        # Loop through all variables that exist
        for s in self.arr_names:
            
            # Variable exists and should be imported, load
            if(s in arr_names):
                filename = self._create_filename(s)
                self._import_vtk(filename, s)
            
            # If variable does not exist in desired output list, delete
            elif(delete_existing and s in self.arr):
                del self.arr[s]
                
                
    def _import_vtk(self, filename, varname, log=False):
        '''Import data into self.arr'''
        
        if self.verbose == True:
            print(' file name = ', filename, varname)

        if not filename.is_file():
            print(f"Can't find file: {filename}")

        else:

            if (self.suffix == 'pvti'):
                reader = vtk.vtkXMLPImageDataReader()
            elif (self.suffix == 'vti'):
                reader = vtk.vtkXMLImageDataReader()
            elif (self.suffix == 'vts'):
                reader = vtk.vtkXMLStructuredGridReader()
            else:
                print('Not supported file type')

            reader.SetFileName(filename)

            #reader.ReadAllVectorsOn()
            #reader.ReadAllScalarsOn()
            #reader.ReadAllTensorsOn()

            reader.Update()

            data = reader.GetOutput()

            extent = data.GetExtent()
            dim = [extent[1] + 1, extent[3] + 1, extent[5] + 1]

            v = vtk_np.vtk_to_numpy(data.GetCellData().GetArray(0))

            if(log):
                v = 10**v
                
            n_comp = data.GetCellData().GetArray(0).GetNumberOfComponents()
            
            vec = [int(i - 1) for i in dim]
            if(n_comp>1):
                vec.append(n_comp)

            self.arr[varname] = v.reshape(vec,order='F')


    def check_restart_streak(self, time, test=False):
        """
        Check where increase in time is not monotonic - corresponds to restarts...
        During a restart there is an initial output when the code restarts, and there
        can then be a second dump if the restart time corresponds to a dump time.
        
        Returns indices which break monoticity.
        """
        
        indices = np.where(np.diff(time) <= 0)[0] + 1
        
        if indices.size == 0:
            groups = []
        else:
            groups = np.split(indices, np.where(np.diff(indices) != 1)[0] + 1)
            if test: print(f"Streak contains {len(groups)} restart(s).")
        
        if test:
            return
        else:
            return groups
    
    
    def delete_restart_streak(self, time, groups=None):
        """
        Find indices to be deleted to keep time monotonic - times are removed which 
        are are later later than the restart time.
        """
        
        if groups is None: groups = self.check_restart_streak(time)
        
        delete_indices = []
        
        for group in groups:
            for i in range(group[-1]):
                if time[i] >= time[group[-1]]:
                    delete_indices.append(i)
                    # print(time[i], i)
            
        return delete_indices
    

    def import_streak(self, arr_names):
        '''Import streak data into self.streaks'''
        
        streak_dict = {}
        
        folder_path = self.run_path / "streaks"
        
        time = np.loadtxt(folder_path / f"{self.simulation}Time.dat")
        streak_dict["time"] = time
        
        self.check_restart_streak(time, test=True) # Check for restarts
        
        for s in arr_names:
            data = np.loadtxt(folder_path / f"{self.simulation}{s}.dat")
            streak_dict[s] = data
        
        self.streaks = streak_dict


    def set_3D_axlim(self, ax):

        ax.set(xlim=[self.x[0], self.x[-1]],

               ylim=[self.y[0], self.y[-1]],

               zlim=[self.z[0], self.z[-1]])

        ax.set_aspect(1)


#%% Main script
if __name__ == "__main__":
    
    ROOTDIR = r"D:/Projects/ICF Summer Internship"
    # ROOTDIR = r"C:/Users/ADearling/source/repos/Code1/"
    # ROOTDIR = r"C:/Users/adearlin/source/repos/Chimera/Code1/"
    
    project = r"Paraview Data"
    simulations = ["xy23"]
    vtk_file = ["vti"]
    
    variables = ["rho_CH"]
    variables_streak = ["Trr"]
    
    Chimera = ChimeraSimulation(ROOTDIR, project)
    
    # run_details = Chimera.get_run_details()
    
    chimera_dat = Chimera.load_dat(simulations[0])

    i=0
    for simulation in simulations:
        Chimera.load_simulation(simulation, suffix=vtk_file[i], geometry=0)
        Chimera.import_timestep(0, arr_names=variables) # Imports the timestep number 'time_to_import'
        print((Chimera.arr.keys()))
        print(Chimera.arr["rho_CH"])
        # Number of cells in each direction
        print(f"X cells: {Chimera.nx}")
        print(f"Y cells: {Chimera.ny}")
        print(f"Z cells: {Chimera.nz}")

        # The actual physical coordinates of the cell boundaries (NumPy arrays)
        print(Chimera.x)
        print(Chimera.y)
        print(Chimera.z)

        # The physical coordinates of the cell centers
        print(Chimera.xc) 
        print(Chimera.yc)
    
    # Chimera.import_streak(variables_streak)